use_frameworks!

target 'MoeLocalizable_Example' do
  pod 'MoeCommon', :git=>'https://github.com/linyanzuo/MoeCommon.git'
  pod 'MoeLocalizable', :path => '../'

  target 'MoeLocalizable_Tests' do
    inherit! :search_paths

    
  end
end
